services:
  server:
    build: 
      context: ./backend
    command: uvicorn src.main:app --reload --host 0.0.0.0 --port 8080
    ports:
      - 8080:8080
    volumes:
      - ./backend:/app

  client:
    build: 
      context: ./frontend
    command: npm run dev
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/app
      - /app/node_modules